name: Crawler Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest
    environment: archive-crawler
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Setup Chrome 114 with browser-actions/setup-chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 114

      - name: Show chromium-browser and chromedriver version after setup
        run: |
          echo ${{ steps.setup-chrome.outputs.chrome-path }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r crawler/requirements.txt

      - name: Ensure chromedriver is executable
        run: chmod +x crawler/chromedriver_linux64/chromedriver

      - name: Check chromedriver permissions
        run: ls -l crawler/chromedriver_linux64/

      - name: Run QOJ Crawler
        run: python3 crawler/qoj/qoj.py
        env:
          PYTHONUNBUFFERED: "1"
          CHROME_BINARY: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
          QOJ_USERNAME: ${{ secrets.QOJ_USERNAME }}
          QOJ_PASSWORD: ${{ secrets.QOJ_PASSWORD }}

      - name: Add and show changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add crawler contests
          git reset HEAD crawler/chromedriver_linux64/chromedriver
          git diff --cached --stat

      - name: Check if contests changed
        id: check_contests
        run: |
          if git diff --cached --name-only | grep '^contests/'; then
            echo "contests_changed=true" >> $GITHUB_ENV
            echo "Detected changes in contests directory."
          else
            echo "contests_changed=false" >> $GITHUB_ENV
            echo "No changes detected in contests directory."
          fi

      - name: Commit and push changes
        run: |
          if [ "$contests_changed" = "true" ]; then
            git commit -m "[auto] [contests-changed] Update contest and submission data"
          else
            git commit -m "[auto] Update contest and submission data"
          fi
          git push
