name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - deploy
    paths:
      - "contests/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy contests to public
        run: |
          mkdir -p public/contests
          cp -r contests/* public/contests/

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
